    int N;
    int k;
    int sum;
    sum = 0;
    print("Enter the value of N: ");
    input(N);
    print("Enter the value of k: ");
    input(k);
    int i;
    for(i=1;i<=N;i+=1) 
    {
        int temp, j;
        temp = i;
        for(j=2;j<=k;j+=1) 
        {
            temp = (temp * i);
        }
        sum = (sum + temp);
    } 
    print("The value of the expression = ");
    println(sum);
    return 0;
